/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

class TennisGame {
    private var player1Score = "LOVE"
    private var player2Score = "LOVE"
    fun score(): String {
        return "$player1Score-$player2Score"
    }

}

fun main() {

}
