/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

data class TennisGame(private val player1Score: String, private val player2score: String) {
    fun score(): String {
        return "${this.player1Score}-$player2score"
    }

    fun player1WinsBall(): TennisGame {
        return this.copy(player1Score = "15")
    }

}

fun main() {

}
