/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class TennisGameTest {

    @Test
    fun `initial score is LOVE-LOVE`() {
        assertThat(TennisGame("LOVE", "LOVE").score()).isEqualTo("LOVE-LOVE")
    }

    @Test
    fun `given current score is LOVE-LOVE, when player1 wins then score should be 15-LOVE`() {
        var tennisGame = TennisGame("LOVE", "LOVE")
        tennisGame = tennisGame.player1WinsBall()
        assertThat(tennisGame.score()).isEqualTo("15-LOVE")
    }

}
